import { describe, expect, it } from 'vitest'
import {
  componentLabelForSelector,
  localizeComponentName,
  localizeMarkupComponentNames,
} from './componentLabels'
import { PAGE_DEFINITION_LIST } from './pageRegistry'

const ENGLISH_UI_TERMS = /\b(?:page background|background image|created by|generated by|generated date|player (?:header|backdrop|information|avatar)|best scores|artwork|history card|task card|command group|command title|command details|calendar day|challenge song|task song|heading|enter|exit)\b/i

describe('component labels', () => {
  it('localizes fixed names and repeated fixture name patterns', () => {
    expect(localizeComponentName('Page background')).toBe('页面背景')
    expect(localizeComponentName('Distorted Fate artwork')).toBe('Distorted Fate 曲绘')
    expect(localizeComponentName('History 8: 2026/08/01')).toBe('历史记录 8：2026/08/01')
    expect(localizeComponentName('12. Spasmodic (exit)')).toBe('12. Spasmodic（退出）')
    expect(localizeComponentName('API 操作 command group')).toBe('API 操作命令分组')
    expect(localizeMarkupComponentNames('<div data-gjs-name="Player backdrop"></div>'))
      .toContain('data-gjs-name="玩家背景曲绘"')
    for (const defaultName of ['Box', 'Svg', 'P', 'Br', 'I', 'Num', 'Article', 'G', 'Defs', 'Marker', 'Polygon', 'Tspan', 'Comment']) {
      expect(localizeComponentName(defaultName), defaultName).toMatch(/[\u3400-\u9fff]/)
    }
  })

  it('gives every registered navigation target a readable Chinese label', () => {
    const unresolved: Array<{ page: string; selector: string; label: string }> = []
    for (const page of PAGE_DEFINITION_LIST) {
      for (const group of page.selectorGroups) {
        for (const selector of group.selectors) {
          const label = componentLabelForSelector(selector, page.markup, group.label)
          if (!label || label === selector || label === `${group.label}元素` || label.startsWith('.')) {
            unresolved.push({ page: page.target, selector, label })
          }
        }
      }
    }
    expect(unresolved).toEqual([])
  })

  it('removes generic English UI names from every page fixture', () => {
    const untranslated = PAGE_DEFINITION_LIST.flatMap((page) => (
      [...page.markup.matchAll(/data-gjs-name="([^"]+)"/g)]
        .map((match) => match[1])
        .filter((name) => ENGLISH_UI_TERMS.test(name))
        .map((name) => ({ page: page.target, name }))
    ))
    expect(untranslated).toEqual([])
  })

  it('does not leave plain-English layer names outside commands, song data, and technical terms', () => {
    const allowed = /^(?:RKS|\/phi(?:\s.*)?)$/
    const untranslated = PAGE_DEFINITION_LIST.flatMap((page) => (
      [...page.markup.matchAll(/data-gjs-name="([^"]+)"/g)]
        .map((match) => match[1])
        .filter((name) => !/[\u3400-\u9fff]/.test(name) && !allowed.test(name))
        .map((name) => ({ page: page.target, name }))
    ))
    expect(untranslated).toEqual([])
  })
})
